/* Sawaaden AI Travel Planner — connects to /api/chat */
(() => {
  const style = document.createElement('link'); style.rel='stylesheet'; style.href='chatbot.css'; document.head.appendChild(style);
  const root = document.createElement('div');
  root.innerHTML = `<button class="sawaaden-ai-launcher" aria-label="Open Sawaaden AI"><span class="sawaaden-ai-icon">✦</span><span class="sawaaden-ai-label">Sawaaden AI<small>Plan your Sikkim trip</small></span></button><section class="sawaaden-ai-panel" aria-label="Sawaaden AI travel planner"><header class="sawaaden-ai-head"><div class="sawaaden-ai-head-main"><span class="sawaaden-ai-avatar">S</span><div><strong>Sawaaden AI</strong><small>Your Sikkim travel planner</small></div></div><button class="sawaaden-ai-close" aria-label="Close">×</button></header><div class="sawaaden-ai-messages"></div><div class="sawaaden-ai-quick"><button class="sawaaden-ai-chip">Best places in Sikkim</button><button class="sawaaden-ai-chip">Plan a 5-day trip</button><button class="sawaaden-ai-chip">Nathula & Tsomgo</button><button class="sawaaden-ai-chip">North Sikkim</button></div><div class="sawaaden-ai-note">AI guidance can change with weather, permits and local access rules.</div><form class="sawaaden-ai-form"><textarea class="sawaaden-ai-input" rows="1" maxlength="1000" placeholder="Ask about Sikkim, packages or your trip..."></textarea><button class="sawaaden-ai-send" aria-label="Send">➤</button></form></section>`;
  document.body.appendChild(root);
  const panel=root.querySelector('.sawaaden-ai-panel'), launcher=root.querySelector('.sawaaden-ai-launcher'), close=root.querySelector('.sawaaden-ai-close'), box=root.querySelector('.sawaaden-ai-messages'), form=root.querySelector('form'), input=root.querySelector('.sawaaden-ai-input'), send=root.querySelector('.sawaaden-ai-send');
  let history=[];
  const add=(text,who='ai')=>{const el=document.createElement('div');el.className=`sawaaden-ai-msg ${who}`;el.textContent=text;box.appendChild(el);box.scrollTop=box.scrollHeight;return el};
  add('Namaste! 👋 I’m Sawaaden AI. I can help you choose Sikkim destinations, compare routes, build an itinerary, and connect you with Sawaaden Tours & Travels. Where would you like to go?');
  const ask=async(text)=>{if(!text.trim()||send.disabled)return;add(text,'user');history.push({role:'user',content:text});input.value='';send.disabled=true;const typing=add('Thinking…','ai');try{const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({messages:history})});if(!r.ok)throw new Error('Request failed');const data=await r.json();typing.remove();const reply=data.message||data.text||'I could not get a response right now. Please try again or contact Sawaaden directly.';add(reply,'ai');history.push({role:'assistant',content:reply});}catch(e){typing.textContent='I’m temporarily unavailable. Please use WhatsApp or call Sawaaden for immediate help.';}finally{send.disabled=false;input.focus();}};
  launcher.onclick=()=>{panel.classList.add('open');input.focus()}; close.onclick=()=>panel.classList.remove('open');
  form.onsubmit=e=>{e.preventDefault();ask(input.value)};
  input.onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();form.requestSubmit()}};
  root.querySelectorAll('.sawaaden-ai-chip').forEach(b=>b.onclick=()=>ask(b.textContent));
})();
